Upgrade to OpenBMC v2.14

diff --git a/meta-facebook/meta-bletchley/recipes-bletchley/motor-ctrl/files/motor-init b/meta-facebook/meta-bletchley/recipes-bletchley/motor-ctrl/files/motor-init
--- a/meta-facebook/meta-bletchley/recipes-bletchley/motor-ctrl/files/motor-init
+++ b/meta-facebook/meta-bletchley/recipes-bletchley/motor-ctrl/files/motor-init
@@ -7,6 +7,9 @@
 
 export PATH=$PATH:/usr/libexec
 
+# shellcheck source=meta-facebook/meta-bletchley/recipes-bletchley/plat-tools/files/bletchley-common-functions
+source /usr/libexec/bletchley-common-functions
+
 PWM_CLASS_PATH="/sys/class/pwm/pwmchip0"
 #Sleld 1~6 using bmc pwm8~13 as motor driver stick
 PWM_NUM_OFFSET=7
@@ -45,42 +48,6 @@ function open_pwm() {
     fi
 }
 
-function set_gpio()
-{
-    NET_NAME=$1
-    OUT_VAL=$2
-    mapfile -t -d " " GPIO_INFO < <(gpiofind "$NET_NAME")
-    if [ "${#GPIO_INFO[@]}" -ne 2 ]; then
-        echo "set_gpio: can not find gpio, $NET_NAME"
-        return 1
-    fi
-    echo -n "set_gpio: set $NET_NAME = $OUT_VAL"
-    if ! gpioset "${GPIO_INFO[0]}" "${GPIO_INFO[1]%$'\n'}"="$OUT_VAL"; then
-        echo " failed"
-        return 1
-    fi
-    echo " success"
-    return 0
-}
-
-function get_gpio()
-{
-    NET_NAME=$1
-    RET_VAL=2
-
-    mapfile -t -d " " GPIO_INFO < <(gpiofind "$NET_NAME")
-    if [ "${#GPIO_INFO[@]}" -ne 2 ]; then
-        echo "get_gpio: can not find gpio, $NET_NAME" >&2
-        return 1
-    fi
-    if ! RET_VAL=$(gpioget "${GPIO_INFO[0]}" "${GPIO_INFO[1]%$'\n'}") ; then
-        echo "get_gpio: get ${NET_NAME} failed" >&2
-        return 1
-    fi
-    echo "${RET_VAL}"
-    return 0
-}
-
 #Init gpio pins for step motor control
 function init_gpios() {
     echo "Init GPIOs:"
@@ -107,8 +74,7 @@ else
 fi
 
 #Check if sled is present
-SLED_PRESENT=$(get_gpio "presence-sled${SLED_NUM}")
-if [ "$SLED_PRESENT" != 0 ];then
+if ! is_sled_present "${SLED_NUM}"; then
     echo "${SLED} is not present, skip motor initialize"
     exit 1
 fi
@@ -124,25 +90,18 @@ DETECT_PIN1="SLED${SLED_NUM}_MS_DETECT1"
 INIT_POS=$(get_gpio "$DETECT_PIN1")
 
 if [ "$INIT_POS" -eq 1 ];then
-    time_count=0
     echo "Making motor back to initial position..."
     motor-ctrl "$SLED" r >/dev/null
-    while  [ "$INIT_POS" -eq 1 ]  ;do
-        INIT_POS=$(get_gpio "$DETECT_PIN1")
-        sleep 0.1
-        time_count=$(( time_count + 1 ))
-        if [  $time_count -gt $CALIBRATE_TIMEOUT ];then
-            echo "Error: Step motor run over 1 cycle but switch never triggered"
-            break
-        fi
-    done
+    wait_gpio_falling "$DETECT_PIN1" "$CALIBRATE_TIMEOUT"
     motor-ctrl "$SLED" s >/dev/null
 fi
 
+INIT_POS=$(get_gpio "$DETECT_PIN1")
 if [ "$INIT_POS" -eq 0 ];then
     echo "Motor calibrated to initial position."
     exit 0
 else
+    echo "Error: Step motor run over 1 cycle but switch never triggered"
     echo "Find motor initial position failed"
     exit 1
 fi
